### PR TITLE
Add detection for Worker API support

### PR DESCRIPTION
**Pull request by jenic**
Small addition to add [Worker API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) detection support. Not sure if useful...

### CODE REVIEW

**Comment by jonashaag** [comment]
Hm. Does this add any entropy over the user agent string? Can web workers be disabled by people? Are they disabled automatically in incognito? Does this somehow depend on your hardware setup?

**Comment by jenic** [comment]
Very good questions I believe in firefox they can be disabled with `dom.workers.enabled` and `dom.serviceworkers.enabled` please correct if wrong. I don't believe they are disabled in incognito. I don't currently have a lot of time to test things, sorry bout that.

**Comment by jonashaag** [comment]
Are you using this in a project and does it help you with fingerprinting your users or did you just think this could be a neat addition to the components? Like, do you have a use case?

**Comment by jenic** [comment]
I'm not currently using this, no. I have plans to use it along with some mobile features coming down the pipeline in future browser releases. I use this project itself for short-term servers of various operating lengths and my specific use case calls for as much identifying information as possible.

I myself am skeptical as to its usefulness and only sent it to you on the off chance you might want it.

**Comment by jonashaag** [comment]
OK, closing this then. If someone thinks this should be added to fingerprintjs, feel free to comment here.

**Pull request closed without merging**
