### PR TITLE
Add maxLength, maxLengthSalt options for performance improvement 

### PR DESCRIPTION
**Pull request by wkdtjsgur100**
I'm sorry, git was twisted, that's why I send you PR again.

# Previous pull request

#347 
 
# Changing log
- Add maxLength, maxLengthSalt option descriptions in README.md
- Add getSubstrByMaxLength, getSalt function
- Add test code

# related issue

#348

### CODE REVIEW

**Comment by jonashaag** [comment]
Great idea. I'm not happy with basing the salting length on user agent though. That way in the (very unlikely) case that you have two different browsers with identical, overly long canvas/GL fingerprints, fingerprints will be different, which makes canvas/GL unnecessarily browser-dependent.

Not sure what an alternative is, give me a few days to think about this or make a suggestion

**Comment by wkdtjsgur100** [comment]
My another suggestion is to apply string compression algorithm that is faster than hash algorithm. However I don't know efficient compression algorithm yet. If I find out it I'll let you know.  Thank you.

**Comment by jonashaag** [comment]
That would be best. How long are the "long" strings you're seeing compared to the "average" strings?

We could also decide the cut position from hashing a few bytes of the canvas/GL fingerprint itself, which makes the cut position not depend on the UA. Maybe not the first few bytes, but maybe bytes 100-110 or whatever.

**Comment by jonashaag** [comment]
Closing due to inactivity.

**Pull request closed without merging**
