### PR TITLE
Bower support & minified version

### PR DESCRIPTION
**Pull request by unDemian**
Hi,
I added your package to bower and also created a minified version + minify gulp task. Right now the bower component links to my fork but if you merge this pull request I will unregister my repo and you could register this one as a bower component.

Also I added 0.1.1 to git tags at the latest commit in order to have semver versioning in place.
Thanks

### CODE REVIEW

**Comment by Valve** [comment]
Thanks, @unDemian :heart:

**Comment by unDemian** [comment]
Sure :)
I unregistered my repo. Can you please add git tag 0.1.1 to github and also register your package 
https://github.com/Valve/fingerprintjs2/pull/27

Thanks

**Comment by Valve** [comment]
Done, thanks

**Comment by unDemian** [comment]
Awesome :+1:

**Pull request merged**
