### PR TITLE
Fonts detection improved performance

### PR DESCRIPTION
**Pull request by lrlinde**
Modified fonts detection algorithm. 
Different spans are generated per font and added at once to the DOM. This minimizes browser reflow.
If a font is detected against one baseFont, the algorithm continues with the next one (originally it was always checking against all baseFonts, even if the font was already detected)

I isolated the fonts detection and tested it against a number of browsers with a very simple DOM (see image). It was around 3.5 times faster with this change.

fontsdetectiontimes

### CODE REVIEW

**Comment by Valve** [comment]
Awesome! 
Thanks for the PR
Please run the gulp to fix the formatting issues and I'll merge

**Comment by lrlinde** [comment]
Sorry about that! Let me know if everything's ok now. 

Thanks!

**Comment by Valve** [comment]
Thanks! I will definitely review it later today and merge.

**Comment by Valve** [comment]
Thank you!

**Comment by lrlinde** [comment]
Thank you, Valve :)

**Comment by m1johnson** [comment]
Nice work!

**Pull request merged**
