### PR TITLE
Fixed module loaders issue. Minor definition changes.

### LINKED ISSUE #146: Uncaught ReferenceError: Fingerprint2 is not defined
I have experienced some problems with Fingerprint2 is not defined, i think it has to do with window.module in some way. I can replicate it every time.

Try this url http://oferta.noznore.es/subscrption-1/

### PR DESCRIPTION
**Pull request by KonstantoS**
Changed some lines in module definition so it should work with module loaders.
This request fixes #146 , and probably #92 (that should be checked with somebody familiar with AMD).
Webpack now works properly with this module. 

I had some errors with AMD requiring, but after this upgrade, they also have gone.

### CODE REVIEW

**Comment by Valve** [comment]
Thanks!
Will review and merge over the weekend

**Comment by vlordier** [comment]
Is there a change it would be pushed to CDNs ?

**Comment by Valve** [comment]
Sorry, let me do it now

**Comment by Valve** [comment]
version 1.4.4 should appear in 10-15 minutes, pushed the release. Thanks for the headsup :+1:

**Comment by oliverlewis** [comment]
Express server listening on port 3000
ReferenceError: Fingerprint2 is not defined.

ReferenceError: Fingerprint2 is not defined
    at /home/server.js:55:7
    at callbacks (/home/node_modules/express/lib/router/index.js:164:37)
    at param (/home/node_modules/express/lib/router/index.js:138:11)
    at pass (/home/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/home/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/home/node_modules/express/lib/router/index.js:33:10)
    at next (/home/node_modules/connect/lib/proto.js:190:15)
    at Object.methodOverride [as handle] (/home/node_modules/connect/lib/middleware/methodOverride.js:49:5)
    at next (/home/node_modules/connect/lib/proto.js:190:15)
    at multipart (/home/node_modules/connect/lib/middleware/multipart.js:85:37)

Used :+1: 
new Fingerprint2().get(function(result, components){
    console.log(result); //a hash, representing your device fingerprint
    console.log(components); // an array of FP components
  });

Version:   
"name": "fingerprintjs2",
  "version": "1.4.4",

Please help!! I'm using Ubuntu 16.10.

Thanks.

**Pull request merged**
