### PR TITLE
Remove gulp dependency

### PR DESCRIPTION
**Pull request by felquis**
Now the steps to run the program is:

```
npm install
npm run build
```

`npm run build` will lint the code with eslint and uglify using uglify-js, the same as before but now with less dependencies

### CODE REVIEW

**Comment by felquis** [comment]
I only did it cause this script is really small, it is so simple that could be done the same without a dependency like gulp.

**Comment by Valve** [comment]
I'm not sure about this change, @felquis . Gulp is a big dependency but a dependency almost any project has. It adds some overhead but the gulpfile is easier to read than your custom script, imo.

**Comment by felquis** [comment]
You are right! I just wanted to give it a try :)

**Comment by Valve** [comment]
thanks @felquis !

**Pull request closed without merging**
