### PR TITLE
Add name property to bower.json

### PR DESCRIPTION
**Pull request by Schinkentanz**
Otherwise a "bower install" isnt possible.

### CODE REVIEW

**Comment by Valve** [comment]
Oh, darn, how could I have missed that, probably removed it accidentally. Thanks, @Schinkentanz

**Comment by Schinkentanz** [comment]
Np :)

**Comment by Valve** [comment]
Do I need to republish it with bower?

**Comment by Schinkentanz** [comment]
Yup. Would be great

**Comment by Valve** [comment]
Done

**Pull request merged**
