### PR TITLE
Add option for user-defined fonts

### PR DESCRIPTION
**Pull request by kevindice**

### CODE REVIEW

**Comment by Valve** [comment]
Why do we need this?

**Comment by kevindice** [comment]
Some users may wish to test for additional fonts to increase the entropy of the font fingerprint.  For my use case, I'd like to test for some of the most popular fonts downloaded from [Font Squirrel](https://www.fontsquirrel.com) and similar sites.

**Comment by Valve** [comment]
Your PR lacks tests and you didn't run the gulp. Please also modify the readme with explanation of this new option.
I also have ~500 of the most popular fonts already in the lib, so I doubt that adding this option will actually improve entropy. Do you have examples of fonts that this library doesn't have and which are really popular?

**Comment by Valve** [comment]
Please don't forget to bring an example of some new fonts you'd like to use with this new option

**Comment by kevindice** [comment]
```
          "Open Sans", "Quicksand", "Alex Brush", "Roboto", "Pacifico", "GoodDog",
          "Great Vibes", "Aller", "Raleway", "ChunkFive", "Lato", "Amatic",
          "Lobster", "Ostrich Sans", "Allura", "PT Sans", "Bebas Neue", "Oswald",
          "Kaushan Script", "League Gothic", "Caviar Dreams", "Source Sans Pro",
          "Grand Hotel", "Titillium", "Windsong", "Sofia", "Montserrat", "Bebas",
          "Museo Slab", "Exo", "Black Jack", "Learning Curve Pro", "FFF Tusj",
          "Walkway", "CAC Champagne", "Lobster Two", "Colaborate",
          "SeasideResort", "Nexa Rust", "Dancing Script OT", "Code Pro",
          "Sansation", "Droid Sans", "Museo Sans", "Capture it", "Arizonia",
          "Sail", "Sofia Pro", "Existence Light", "Journal"
```

**Comment by Valve** [comment]
Thanks, will review and merge soon!

**Pull request merged**
