### PR TITLE
Performance: only call toLowerCase() once per variable

### PR DESCRIPTION
**Pull request by blx**
Tiny change to the `getHasLied` functions to only call `toLowerCase()` once per variable, instead of repeatedly.

I can add the minified gulp output if you'd like, I wasn't sure if you wanted to do that yourself.

Cheers,
Ben

### CODE REVIEW

**Comment by Valve** [comment]
Out of the country now will merge in several days

**Comment by Valve** [comment]
@blx , thanks, very nice readability update as well!

**Comment by blx** [comment]
Glad to contribute! :)

**Comment by Valve** [comment]
released new version

**Pull request merged**
