### PR TITLE
Feature/exclude local storage

### PR DESCRIPTION
**Pull request by wkdtjsgur100**
this.options.excludeSessionStorage -> this.options.excludeLocalStorage in localStorageKey function

### CODE REVIEW

**Comment by jonashaag** [comment]
I'm not happy with this change, it's trivial but breaks people's code. We could do it in a backwards compatible way by supporting the old option as well. Btw there's a typo in your code :)

**Comment by wkdtjsgur100** [comment]
Oh I got it. Thank you for the feedback!

**Comment by jonashaag** [comment]
Sorry, maybe I wasn't clear, let's rename it but keep the old name as well. But let's wait a few days since there's another PR on renaming exclude* options ATM

**Comment by jonashaag** [comment]
Closing due to inactivity.

**Pull request closed without merging**
