### PR TITLE
Updating v2 to merge user given options with default options.

### PR DESCRIPTION
**Pull request by seansehr**

### CODE REVIEW

**Comment by Valve** [comment]
This is a good refactoring, but it's a breaking change, so I won't be able to merge this until v2 is ready

**Comment by jonashaag** [comment]
@Valve isn't this just bike shedding? Does this really help in some use cases? It's just another representation of the exact same information.

**Comment by elad-yosifon** [comment]
@jonashaag  I will try to finish this version until this weekend..  my apologies for the long delay.

**Comment by Valve** [comment]
@jonashaag I'm not sure if many people exclude many options. Can be useful if developers do it frequently. If not, then yeah, not worth adding.

**Comment by jonashaag** [comment]
OK, I'm -1 on this:

- It's backwards incompatible
- It's essentially bike shedding.

**Pull request closed without merging**
